# This file is used by the dorny/paths-filter action to figure out if a program or
# client has changed and thus if it should be built or tested. Any changes in the
# files listed below will trigger the appropriate workflow for that program or client.

# Programs.

program_common: &program_common
  - ".github/workflows/build-programs.yml"
  - ".github/workflows/test-programs.yml"
  - ".github/workflows/main.yml"
  - ".github/file-filters.yml"
  - ".github/.env"

asset_program: &asset_program
  - *program_common
  - "programs/asset/**"

bridge_program: &bridge_program
  - *program_common
  - "programs/bridge/**"

programs: &programs
  - *asset_program
  - *bridge_program

# Clients.

client_common: &client_common
  - *programs
  - ".github/workflows/test-js.yml"
  - ".github/workflows/test-rust-client.yml"
  - ".github/workflows/build-rust-client.yml"
  - ".github/workflows/main.yml"
  - ".github/file-filters.yml"
  - ".github/.env"
  - "configs/shank.cjs"
  - "configs/kinobi.cjs"

asset_js_client: &asset_js_client
  - *client_common
  - "clients/asset/js/**"

bridge_js_client: &bridge_js_client
  - *client_common
  - "clients/bridge/js/**"

asset_rust_client: &asset_rust_client
  - *client_common
  - "clients/asset/rust/**"

bridge_rust_client: &bridge_rust_client
  - *client_common
  - "clients/bridge/rust/**"

clients: &clients
  - *asset_js_client
  - *asset_rust_client
  - *bridge_js_client
  - *bridge_rust_client

# CLIs.

cli_common: &cli_common
  - *programs
  - *clients
  - ".github/workflows/build-rust-cli.yml"

rust_cli: &rust_cli
  - *client_common
  - "clients/cli/**"

clis: &clis
  - *rust_cli

# Any.

any: &any
  - *programs
  - *clients
  - *clis
