name: Build Rust Client

on:
  workflow_call:
    inputs:
      client_matrix:
        type: string
      rust:
        type: string
      solana:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.70.0
        required: true
        type: string
      solana:
        description: Solana version
        default: 1.16.18
        required: true
        type: string

env:
  CACHE: true

jobs:
  build_sdk:
    name: Build
    runs-on: buildjet-16vcpu-ubuntu-2204
    strategy:
      matrix:
        client: ${{ fromJson(inputs.client_matrix) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: ./.github/actions/install-rust
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Install Solana
        uses: ./.github/actions/install-solana
        with:
          version: ${{ inputs.solana || env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache Rust client test dependencies
        uses: ./.github/actions/cache-crate
        with:
          folder: ./clients/${{ matrix.client }}/rust
          key: ${{ matrix.client }}-rust-client-test

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args:
            --all-targets --all-features --no-deps --manifest-path ./clients/${{ matrix.client
            }}/rust/Cargo.toml

      - name: Build Rust client
        shell: bash
        working-directory: clients/${{ matrix.client }}/rust
        run: cargo build --all-features --release

      - name: Upload Rust client builds
        uses: actions/upload-artifact@v3
        with:
          name: rust-client-builds
          # First wildcard ensures exported paths are consistently under the clients folder.
          path: ./client*/${{ matrix.client }}/rust/target/release/*${{ matrix.client }}*
          if-no-files-found: error
