name: Test Rust Client

on:
  workflow_call:
    inputs:
      client_matrix:
        type: string

env:
  CACHE: true

jobs:
  test_sdk:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client: ${{ fromJson(inputs.client_matrix) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: ./.github/actions/install-rust
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Solana
        uses: ./.github/actions/install-solana
        with:
          version: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache Rust client test dependencies
        uses: ./.github/actions/cache-crate
        with:
          folder: ./clients/${{ matrix.client }}/rust
          key: ${{ matrix.client }}-rust-client-test

      - name: Download program builds
        uses: actions/download-artifact@v3
        with:
          name: program-builds

      - name: Run tests
        shell: bash
        working-directory: configs/scripts/client
        run: RUST_LOG=error ./test-rust.sh ${{ matrix.client }}
